# Generated by Django 6.0.5 on 2026-05-12 18:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=4096, null=True)),
                ('private', models.BooleanField(default=False)),
                ('hypothetical', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('work_in_progress', 'Work In Progress'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='work_in_progress', max_length=32)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-created_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('observing_system', 'Observing System'), ('data_product', 'Data Product'), ('application', 'Application'), ('societal_benefit_area', 'Societal Benefit Area')], max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=4096, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('organization', models.CharField(blank=True, max_length=256, null=True)),
                ('funder', models.CharField(blank=True, max_length=256, null=True)),
                ('funding_country', models.CharField(blank=True, max_length=256, null=True)),
                ('website', models.URLField(blank=True, max_length=256, null=True)),
                ('contact_information', models.CharField(blank=True, max_length=256, null=True)),
                ('persistent_identifier', models.CharField(blank=True, max_length=256, null=True)),
                ('hypothetical', models.BooleanField(default=False)),
                ('framework_name', models.CharField(blank=True, max_length=256, null=True)),
                ('framework_url', models.URLField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes (Object Library)',
                'ordering': ['type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_nodes', to='vta.assessment')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_instances', to='vta.node')),
            ],
            options={
                'verbose_name': 'Assessment Node',
                'verbose_name_plural': 'Assessment Nodes',
                'ordering': ['node__type', 'node__title'],
                'unique_together': {('assessment', 'node')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcid', models.CharField(blank=True, max_length=64, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_nodes', to='vta.userprofile'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to='vta.userprofile'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1-100', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('criticality_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('performance_rating_rationale', models.TextField(blank=True, max_length=8192, null=True)),
                ('criticality_rating_rationale', models.TextField(blank=True, max_length=8192, null=True)),
                ('gaps_description', models.TextField(blank=True, max_length=8192, null=True)),
                ('attribute_description', models.CharField(blank=True, max_length=512, null=True)),
                ('source_assessment_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_links', to='vta.assessmentnode')),
                ('target_assessment_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_links', to='vta.assessmentnode')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links (Value Tree Edges)',
                'unique_together': {('source_assessment_node', 'target_assessment_node')},
            },
        ),
    ]
